name: Publish

on:
  push:
    branches: [master]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pkg:
          - modules/sdk
          - modules/sdk-react

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - name: Build
        working-directory: ${{ matrix.pkg }}
        run: npm run build

      - name: Publish if new version
        working-directory: ${{ matrix.pkg }}
        run: |
          NAME=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")
          
          echo "Checking for existence of $NAME@$VERSION in npm registry"
          if npm view "$NAME@$VERSION" version >/dev/null 2>&1; then
            echo "Already published: $NAME@$VERSION"
            exit 0
          fi
          
          echo "Not published yet. Publishing $NAME@$VERSION"
          NODE_AUTH_TOKEN="" npm publish --access public
